### PR TITLE
modify deployment cancel message

### LINKED ISSUE #1495: 🐛 Bug Report: Cancelling a deployment shows wrong message
### 👟 Reproduction steps

1. Go to Project > Functions
2. Create a deployment
3. Click on 3 dots menu of the processing deployment
4. Click on `Cancel`
5. Notification shows - `Deployment has been deleted`

### 👍 Expected behavior

Notification should show - `Deployment cancelled` or similar.

### 👎 Actual Behavior

Notification shows wrong message - `Deployment has been deleted`

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by pushkar707**
## What does this PR do?

Fixes #1495 

## Test Plan

You can verify the changes, by adding a deployment to a function, and immediately cancel it. With changes made, you will see the message 'Deployment cancelled' in place of 'Deployment has been deleted'

## Related PRs and Issues
None

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

File: src/routes/(console)/project-[project]/functions/function-[function]/cancel.svelte [hunk 1]
```diff
@@ -21,7 +21,7 @@
             showCancel = false;
             addNotification({
                 type: 'success',
-                message: `Deployment has been deleted`
+                message: `Deployment cancelled`
```
Comment (ItzNotABug) [inline src/routes/(console)/project-[project]/functions/function-[function]/cancel.svelte:24]:
```suggestion
                message: `Deployment has been cancelled`
```

**Review by ItzNotABug — CHANGES_REQUESTED** [review]

**Review by ItzNotABug — APPROVED** [review]
