### PR TITLE
Fix: display version in the footer on local instance

### LINKED ISSUE #1997: 🚀 Enhancement: Bring back the current Version in the footer
### 🔖 Enhancement description

in Appwrite versions 1.6.x we had the current installed version of appwrite shown like this: Version: 1.6.2 and when we pressed it we would be forwarded to the current releases of appwrite.

### 🎤 Pitch

I would love to have this feature returned because so I could easy lookup if my current instance (I have multiple) already is up to date or I need to update it, when I do a new deployment of my app. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by tejas-raskar**
## What does this PR do?
Displays the current version in the footer on local instances similar to that on cloud instances.

## Test Plan
- Ran `pnpm run tests`, `pnpm run checks`, `pnpm run lint`, and `pnpm run format` to maintain the code quality. 
- Verified using separate browsers to confirm the changes work as expected. Here are the results -  

Desktop view:
Screenshot From 2025-07-10 00-55-33

For `$isSmallViewport`, I tried to maintain the same design as that of the cloud version. The version is shown on the separate line instead of the same line as desktop view.

Mobile view:
Screenshot From 2025-07-10 00-55-55

## Related PRs and Issues

Fixes #1997 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by docimin** [comment]
Maybe it's a smart idea to put the version to the right of Privacy, instead of below, as well as remove the seperator in mobile, so this actually looks mobile friendly?
image

**Comment by tejas-raskar** [comment]
I tried to keep it consistent with the cloud version. But I too think version besides Privacy is a good idea. This is how the cloud version looks like:

image

**Comment by HarshMN2345** [comment]
@tejas-raskar Thanks for the PR! We'll confirm with our design team and get back to you shortly. Appreciate your contribution! 🙌

**Comment by HarshMN2345** [comment]
> I tried to keep it consistent with the cloud version. But I too think version besides Privacy is a good idea. This is how the cloud version looks like:
> 
> image

Hey @tejas-raskar,
I checked with the design team and they suggested a small improvement, can we make it a bit smarter so that the version only moves to the next line if there's not enough space to keep it in the first row?

Instead of always rendering the version on a new line for small viewports, we could improve the layout by letting it stay in the first row unless there isn’t enough space.

**Comment by tejas-raskar** [comment]
@HarshMN2345 Great! I will do the required changes and commit it on this branch itself. 
Thanks for confirming.

**Comment by tejas-raskar** [comment]
I made the version inline with the other links as requested and also added the `wrap` prop to make the footer wrap around when the text overflows.

https://github.com/user-attachments/assets/e9fb247b-7d41-436d-a362-4860b76b4834

**Comment by tejas-raskar** [comment]
@HarshMN2345  The test is failing due to some other errors in files that are not touched by this PR. I can only see one warning relevant to this PR which is removing of the unused CSS. How should I proceed?

**Comment by HarshMN2345** [comment]
Hey @tejas-raskar 
The appwrite is GA now, so swap the “Beta” badge for “Generally Available,” which is also causing the merge conflicts. Noticed in the video that the copyright/rights section wraps in some viewports despite having space; worth adjusting.
image

Once those are updated and conflicts resolved, we should be good to go. Thanks again for your contribution! 🙌

File: src/lib/layout/footer.svelte [hunk 1]
```diff
@@ -54,52 +54,30 @@
...
             direction="row"
             justifyContent={$isSmallViewport ? 'flex-start' : 'flex-end'}
-            alignItems="center">
-            {#if isCloud}
-                {#if !$isSmallViewport}<Badge size="xs" variant="secondary" content="BETA" /><Icon
+            alignItems="center"
+            wrap="wrap">
+            {#if !$isSmallViewport}
+                {#if isCloud}
+                    <Badge size="xs" variant="secondary" content="BETA" />
```
Comment (HarshMN2345) [inline src/lib/layout/footer.svelte]: We should replace the "BETA" badge with "Generally Available" here, consistent with how it’s already done elsewhere.

**Review by HarshMN2345 — CHANGES_REQUESTED** [review]

**Comment by tejas-raskar** [comment]
@HarshMN2345 Updated the badge to "Generally Available" and have fixed the copyright/rights section wrap issues. Here are the videos for both when the `isCloud` is true and false

https://github.com/user-attachments/assets/39487439-87fc-4912-ad2e-833fb7f04685


https://github.com/user-attachments/assets/20175cdb-f303-4cfd-a7eb-72812fa661a9

I ran `pnpm run check` and it had errors for other files, probably because this branch is now not updated with the main. Do I need to rebase it to main or there is some other way to resolve these errors?

File: src/lib/layout/footer.svelte (hunk 1 above)
Comment (tejas-raskar) [reply src/lib/layout/footer.svelte]: Resolved this in the recent commit.

**Comment by HarshMN2345** [comment]
@tejas-raskar , could you run pnpm format to address the lint errors showing up in the checks?

**Comment by HarshMN2345** [comment]
> @HarshMN2345 I had already ran both the `pnpm run format` and `pnpm run lint` commands as given in the `CONTRIBUTING.md`. I ran it again now, and no errors. Don't know whats causing the build to fail. Here are the result of both of these - 
> 
> Screenshot From 2025-08-13 22-51-17
> 
> image
> 

Got it, thanks for checking. Could you push again? Your branch had merge conflicts earlier, but I’ve updated it now.

**Comment by tejas-raskar** [comment]
@HarshMN2345 Yeah, had to pull the merge commit and ran the `pnpm run lint` again. Had a extra line at the end of the file. It should be able to pass the test now

**Review by ItzNotABug — APPROVED** [review]
