### PR TITLE
fix: responsive layout for input fields and tables on mobile devices

### LINKED ISSUE #2629: 🐛 Bug: Input fields and extension tags overflow on small devices in bucket settings, platforms table, and messaging providers table
### 👟 Reproduction steps

1. Navigate to the bucket settings page on a mobile or small tablet screen (< 768px):
   - Path: `/project-[region]-[project]/storage/bucket-[bucket]/settings`
2. Scroll to the "Allowed file extension" section
3. Observe the input field and extension tags overflowing horizontally
4. Navigate to the platforms overview page on mobile/tablet:
   - Path: `/project-[region]-[project]/overview/platforms`
5. Observe the table overflowing horizontally on smaller screens
6. Navigate to the messaging providers page on mobile/tablet:
   - Path: `/project-[region]-[project]/messaging/providers`
7. Observe the providers table overflowing horizontally on smaller screens

### 👍 Expected behavior

- Input fields should respect container boundaries and resize properly on small screens
- Extension tags should wrap to new lines instead of overflowing
- All tables (Platforms, Messaging Providers, etc.) should be horizontally scrollable with proper column sizing
- All elements remain responsive across all device sizes

### 👎 Actual Behavior

- InputTags component overflows horizontally on small screens
- Suggested extension tags break layout by extending beyond viewport
- Platform table columns compress improperly, making content unreadable
- Messaging Providers table also overflows horizontally with no scroll behavior
- No horizontal scroll available for table on mobile devices

### 📸 Screenshots

| Page / Section | Before (Current Issue) | After (Fixed - Local Build) |
|----------------|------------------------|------------------------------|
| Storage Page - Bucket Settings Section (Mobile) | Bucket Settings Mobile Before | Bucket Settings Mobile After |
| Overview Page - Platforms Section (Mobile) | Platforms Table Mobile Before | Platforms Table Mobile After |
| Messaging Page - Providers Section (Mobile) | Messaging Providers Mobile Before | Messaging Providers Mobile After |

> **Note:** The "After" screenshots are from my local build.

### 🎲 Appwrite version

Version 1.8.x

### 💻 Operating system

Windows

### 🧱 Your Environment

- Browser: Chrome 142.0.7444.60 (Official Build) (64-bit)
- OS: Windows 11 Home (Version 24H2, Build 26100.6584)
- Console Version: 1.8.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by AbhiVarde**
### Problem
Three console pages had responsive layout issues on mobile and tablet viewports (< 768px):
- **Bucket Settings:** InputTags component and extension tags overflowed horizontally beyond viewport
- **Platforms Table:** Columns compressed improperly with no horizontal scroll, making content unreadable
- **Messaging Providers Table:** Table overflowed horizontally with no scroll functionality

### Solution
Implemented responsive fixes across all three pages:
- Wrapped InputTags in a flex container with proper width constraints and wrapping behavior
- Added horizontal scroll containers with touch-friendly scrolling for both tables
- Configured explicit grid column sizing with minimum widths to maintain readability
- Ensured all elements respect container boundaries on small screens

### Changes Made

**Files Modified:**

1. `src/routes/(console)/project-[region]-[project]/storage/bucket-[bucket]/settings/page.svelte`
   - Wrapped InputTags in container with `min-width: 0; width: 100%;`
   - Added `flex-wrap: wrap; overflow-x: auto;` to extension tags

2. `src/routes/(console)/project-[region]-[project]/overview/platforms/page.svelte`
   - Added `.table-scroll-wrapper` with horizontal scroll and SCSS grid styles

3. `src/routes/(console)/project-[region]-[project]/messaging/providers/table.svelte`
   - Added `.table-scroll-wrapper` with horizontal scroll and SCSS grid styles

## Test Plan
- ✅ Chrome DevTools mobile simulation
- ✅ Physical device testing (Chrome 142.0.7444.60 on Windows 11)
- ✅ Tablet viewports (768px - 1024px)
- ✅ Desktop layout verification (no regressions)
- ✅ Touch scrolling functionality on all affected tables

## Screenshots

| Page / Section | Before (Current Issue) | After (Fixed) |
|----------------|------------------------|---------------|
| Storage Page - Bucket Settings Section (Mobile) | Bucket Settings Mobile Before | Bucket Settings Mobile After |
| Overview Page - Platforms Section (Mobile) | Platforms Table Mobile Before | Platforms Table Mobile After |
| Messaging Page - Providers Section (Mobile) | Messaging Providers Mobile Before | Messaging Providers Mobile After |

## Related PRs and Issues
Fixes #2629

### Have you read the [Contributing Guidelines](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
Yes, I have read and followed the contributing guidelines.

## Summary by CodeRabbit

* **New Features**
  * Platform overview now supports dynamic column configuration for improved flexibility

* **Bug Fixes**
  * Fixed file extension tags not wrapping properly in bucket settings

* **Style**
  * Enhanced column width optimization across tables for better visual presentation and readability

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/routes/(console)/project-[region]-[project]/messaging/providers/table.svelte [hunk 1]
```diff
@@ -39,51 +39,68 @@
...
-    resource="provider"
-    columns={$columns}
-    onDelete={handleDelete}
-    allowSelection={$canWriteProviders}>
-    {#snippet header(root)}
-        {#each $columns as { id, title }}
-            <Table.Header.Cell column={id} {root}>{title}</Table.Header.Cell>
-        {/each}
-    {/snippet}
+<div class="table-scroll-wrapper">
```
Comment (ItzNotABug) [inline src/routes/(console)/project-[region]-[project]/messaging/providers/table.svelte]: we don't need to add custom classes here, best to add `width: { min: xxx }` on the columns itself. You can easily search for the most commonly used dimensions.
Same for table on Overview as well 👍

File: src/routes/(console)/project-[region]-[project]/messaging/providers/table.svelte [hunk 2]
```diff
@@ -39,51 +39,68 @@
...
+        -webkit-overflow-scrolling: touch;
+
+        :global([role='table']) {
+            display: grid;
+            grid-template-columns:
+                minmax(60px, 0.5fr) minmax(200px, 2.5fr) minmax(120px, 1fr) minmax(120px, 1fr)
+                minmax(120px, 1fr) minmax(120px, 1.5fr);
+            width: 100%;
+        }
+    }
```
Comment (ItzNotABug) [inline src/routes/(console)/project-[region]-[project]/messaging/providers/table.svelte]: not needed as per the comment above.

File: src/routes/(console)/project-[region]-[project]/overview/platforms/+page.svelte [hunk 3]
```diff
@@ -121,41 +121,43 @@
...
-                    {#if platform.$updatedAt}
-                        <DualTimeView time={platform.$updatedAt} />
-                    {:else}
-                        never
-                    {/if}
-                </Table.Cell>
-            </Table.Row.Link>
-        {/each}
-    </Table.Root>
+    <div class="table-scroll-wrapper">
```
Comment (ItzNotABug) [inline src/routes/(console)/project-[region]-[project]/overview/platforms/+page.svelte]: same as above.

File: src/routes/(console)/project-[region]-[project]/storage/bucket-[bucket]/settings/+page.svelte [hunk 4]
```diff
@@ -411,13 +411,15 @@
             <svelte:fragment slot="aside">
                 <Layout.Stack gap="s">
                     {#key extensions.length}
-                        <InputTags
-                            id="user-labels"
-                            label="Labels"
-                            placeholder="Select or type user labels"
-                            bind:tags={extensions} />
+                        <div style="min-width: 0; width: 100%;">
```
Comment (ItzNotABug) [inline src/routes/(console)/project-[region]-[project]/storage/bucket-[bucket]/settings/+page.svelte]: this is not needed, the overflow is due to the Stack below.

File: src/routes/(console)/project-[region]-[project]/storage/bucket-[bucket]/settings/+page.svelte [hunk 5]
```diff
@@ -411,13 +411,15 @@
...
+                            <InputTags
+                                id="user-labels"
+                                label="Labels"
+                                placeholder="Select or type user labels"
+                                bind:tags={extensions} />
+                        </div>
                     {/key}
-                    <Layout.Stack direction="row">
+                    <Layout.Stack direction="row" style="flex-wrap: wrap; overflow-x: auto;">
```
Comment (ItzNotABug) [inline src/routes/(console)/project-[region]-[project]/storage/bucket-[bucket]/settings/+page.svelte]: you can just do `<Layout.Stack direction="row" wrap="wrap">`.

**Review by ItzNotABug — CHANGES_REQUESTED** [review]

File: src/routes/(console)/project-[region]-[project]/overview/platforms/+page.svelte (hunk 3 above)
Comment (AbhiVarde) [reply src/routes/(console)/project-[region]-[project]/overview/platforms/+page.svelte]: Hey @ItzNotABug, the overview platforms table originally had no `columns` in store.ts, so I added them with `width: { min: xxx }` and made the header dynamic:
```typescript
// store.ts - newly added
export const columns = writable<Column[]>([
    { id: 'name', title: 'Name', type: 'string', width: { min: 120 } },
    // ...
]);
```
```svelte
<!-- page.svelte - made dynamic -->
{#each $columns as column}
    <Table.Header.Cell {root} column={column.id}>
        {column.title}
    </Table.Header.Cell>
{/each}
```

However, unlike the messaging table which uses `MultiSelectionTable`, this uses `Table.Root` directly, so the `width` properties don't get applied and overflow still appears.

Should I keep the current wrapper classes, or is there another approach for `Table.Root`?

Comment (ItzNotABug) [reply src/routes/(console)/project-[region]-[project]/overview/platforms/+page.svelte]: @AbhiVarde 
make sure to apply the created columns on the `Table.Root` as well like `<Table.Root columns={$columns} let:root>`

Comment (AbhiVarde) [reply src/routes/(console)/project-[region]-[project]/overview/platforms/+page.svelte]: Works perfectly, thanks! 🎉

**Comment by AbhiVarde** [comment]
All review comments addressed, ready for another look! 🙏
cc: @ItzNotABug

**Review by ItzNotABug — APPROVED** [review]
