### PR TITLE
fix: prevent duplicate repository connection notifications

### LINKED ISSUE #2472: 🐛 Bug: Duplicate "Repository connected successfully" notification
### 👟 Reproduction steps

1. Go to Functions and create/select a function
2. Navigate to Settings > Git repository
3. Click "Connect repository"
4. Select an existing repository from the list
5. Observe that the success notification appears twice

**Same issue occurs for Sites.**

### 👍 Expected behavior

After connecting a Git repository, only one success message (“Repository connected successfully”) should appear.

### 👎 Actual Behavior

The success message (“Repository connected successfully”) appears twice after connecting a repository.

### 🎲 Appwrite version

Version 1.8.x

### 💻 Operating system

Windows

### 🧱 Your Environment

- Browser: Chrome 122.0.6261.112 (Official Build) (64-bit)
- OS: Windows 11 Home (Version 24H2, Build 26100.6584)
- Console Version: 1.8.0
- Environment: Local development (localhost:3000)

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by AbhiVarde**
### Problem

The `connectRepo()` function was being called twice:

1. Directly in the repository selection callback
2. Via the modal’s `onSubmit`

This caused the success notification to appear twice, leading to a confusing UX.

### Solution

Removed the extra `connectRepo()` call in the repository selection handler. Now, the modal’s `onSubmit` handles everything, so the function runs only once.

This is a minimal and clean fix addressing the root cause instead of patching the symptom.

### Changes Made

* Removed direct `connectRepo()` call in the repository selection callback
* Kept modal’s `onSubmit` as the single source of truth

### Local Testing Performed:

1. ✅ Connected existing repository to function - notification appears once
2. ✅ Connected existing repository to site - notification appears once
3. ✅ Created new repository for function - notification appears once
4. ✅ Created new repository for site - notification appears once
5. ✅ Verified button disables during connection
6. ✅ Tested error scenarios - flag resets properly
7. ✅ Tested rapid clicking - prevented by disabled button
8. ✅ Ran `pnpm lint` and `pnpm format` - all checks passed

### Screenshots

**Before Fix:**
Screenshot 2025-10-14 192403

**After Fix:**
Screenshot 2025-10-14 192601

## Related PRs and Issues

Fixes #2472 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes, I have read and followed the contributing guidelines.

## Summary by CodeRabbit

* **Bug Fixes**
  * Prevents accidental repository connections when selecting a repo; repositories are only linked after you explicitly submit the modal.
  * Reduces unintended repeated connection attempts by requiring a deliberate submit action.

* **Refactor**
  * Streamlined connection flow so linking is predictable and only triggered via the modal submit, improving clarity of the UI behavior.

### CODE REVIEW

File: src/lib/components/git/connectRepoModal.svelte [hunk 1]
```diff
@@ -53,6 +54,9 @@
     });
 
     async function connectRepo() {
+        if (isConnecting) return;
+        isConnecting = true;
```
Comment (Meldiron) [inline src/lib/components/git/connectRepoModal.svelte]: This is great approach for solving a lot of UX issues 💯

I would fully agree with his, if it was user clicking button twice, causing this.

Problem is, here it seems to be hapening automatically - you click once, but this function seems to be called twice. Internally, something is going on, causing this issue.

Let's please debug a bit further, to find the root cause. I think knowing that, we will find nicer solution at the source, instead of preventing the outcome with a patch

Comment (AbhiVarde) [reply src/lib/components/git/connectRepoModal.svelte]: Thanks for the review, Sir! 🙏

You were right, the function was being called twice because `connectRepo()` was triggered both on repository selection and the modal’s `onSubmit`. I’ve removed the extra call so now it runs only once via `onSubmit`.

Updated the PR, please have a look when you get a chance.

**Comment by stnguyen90** [comment]
@AbhiVarde would you please update your branch to fix the tests?

**Comment by AbhiVarde** [comment]
> @AbhiVarde would you please update your branch to fix the tests?

Done, sir! I’ve updated the branch with the latest changes.

**Review by stnguyen90 — APPROVED** [review]
